[Variables]

;----------------------Dock Settings--------------------------
;-------------------------------------------------------------


Icon1NameAndPath=#@#\My Computer.png
Icon1Text=My Computer
LocationPath1=[Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]

Icon2NameAndPath=#@#\My Documents.png
Icon2Text=My Documents
LocationPath2=[Shell:::{A8CDFF1C-4878-43be-B5FD-F8091C1C60D0}]

Icon3NameAndPath=#@#\Recycle Bin.png
Icon3Text=Recycle Bin
LocationPath3=["shell:RecycleBinFolder"]

Icon4NameAndPath=#@#\Pictures.png
Icon4Text=Pictures
LocationPath4=[Shell:::{3ADD1653-EB32-4cb0-BBD7-DFA0ABB5ACCA}]

Icon5NameAndPath=#@#\Music.png
Icon5Text=Music
LocationPath5=[Shell:::{1CF1260C-4DD0-4ebb-811F-33C572699FDE}]

Icon6NameAndPath=#@#\Downloads.png
Icon6Text=Downloads
LocationPath6=[Shell:::{374DE290-123F-4565-9164-39C4925E467B}]

Icon7NameAndPath=#@#\Google.png
Icon7Text=Google
LocationPath7=!Execute ["https://google.com"]

Icon8NameAndPath=#@#\Facebook.png
Icon8Text=Facebook
LocationPath8=!Execute ["https://facebook.com/"]

Icon9NameAndPath=#@#\Gmail.png
Icon9Text=Gmail
LocationPath9=!Execute ["https://mail.google.com/mail/"]

Icon10NameAndPath=#@#\Twitter.png
Icon10Text=Twitter
LocationPath10=!Execute ["https://www.twitter.com"]



